# This is an example. Please change the configuration variables listed here.
#
# This example uses a volume to persist the sqlite database outside of the container,
# please adapt the local path.  If you use a custom PUID and PGID, you need to create
# the local path beforehand with the correct user/group.
#
# You can generate an admin password with: docker run -it --rm --entrypoint ihatemoney ihatemoney/ihatemoney:latest generate_password_hash
# IMPORTANT: replace every dollar character in the result with a double dollar ($ -> $$)
# To disable admin access, simply set the password to an empty string (ADMIN_PASSWORD=)
#
# See https://ihatemoney.readthedocs.io/en/latest/configuration.html to understand all settings.

version: "3.9"

services:
  ihatemoney:
    image: ihatemoney/ihatemoney:latest
    env_file:
      - stack.env
    volumes:
      - /home/ihatemoney/ihatemoney.db:/database
    ports:
      - "8000:8000"